server:
    port: 8080
spring:
    datasource:
        url: jdbc:h2:mem:memDB
        driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    thymeleaf:
        cache: false